apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: 851966755265.dkr.ecr.eu-west-1.amazonaws.com/sumit:website

---
kind: Service
apiVersion: v1
metadata:
  name: webapp
spec:
  type: LoadBalancer
  selector:
   app: webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
