global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['a4e4af28b8a2011e9a5770a8942135dc-312107872.eu-west-1.elb.amazonaws.com:80']